name: Cypress Tests

on:

  push:

    branches:

      - main

jobs:

  cypress-run:

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: my-cypress-project

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:

          node-version: 20

      - uses: cypress-io/github-action@v6

        with:

          working-directory: my-cypress-project